spring.datasource.url=jdbc:mysql://localhost:3306/ems
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.cloud.stream.bindings.employeeEvent-out-0.destination=employee-events
spring.cloud.stream.kafka.binder.brokers=3.111.58.18:9092
