# MySQL
app.datasource.mysql.url=jdbc:mysql://localhost:3306/ems
app.datasource.mysql.username=root
app.datasource.mysql.password=root
app.datasource.mysql.driver-class-name=com.mysql.cj.jdbc.Driver

# H2 fallback
app.datasource.h2.url=jdbc:h2:mem:fallbackdb;DB_CLOSE_DELAY=-1
app.datasource.h2.username=sa
app.datasource.h2.password=
app.datasource.h2.driver-class-name=org.h2.Driver

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.hibernate.ddl-auto=update